language: node_js
node_js:
  - "6"

sudo: required

before_install:
  - cd $TRAVIS_BUILD_DIR

install:
  - ./tools/travis/setupscan.sh
  - cd $TRAVIS_BUILD_DIR
  - ./tools/travis/unitsetup.sh
  - cd $TRAVIS_BUILD_DIR

script:
  - ./tools/travis/scancode.sh
  - cd $TRAVIS_BUILD_DIR
  - ./tools/travis/unit.sh
