language: node_js
node_js:
  - "6"
  - "4"

# before_install:
  # - apt-get -y install python-pip
  # - pip install --upgrade pip

install:
  - ./tools/travis/setupscan.sh

script:
  - ./tools/travis/scancode.sh