language: node_js
node_js:
  - "6"

sudo: required

services:
 - docker

before_install:
  - cd $TRAVIS_BUILD_DIR

install:
  - ./tools/travis/setupscan.sh
  - cd $TRAVIS_BUILD_DIR
  - ./tools/travis/setup.sh
  - cd $TRAVIS_BUILD_DIR

script:
  - npm run lint
  - ./tools/travis/scancode.sh
  - cd $TRAVIS_BUILD_DIR
  - ./tools/travis/build.sh
